spring:
  application:
    name: tubine
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://db-p1000031668.ZZYT.com:8000/eureka/
turbine:
  appConfig: CONSUMER
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

management:
  endpoints:
    web:
      exposure:
        exclude: "*"