spring:
  application:
    name: consumer
  mvc:
    view:
      prefix: /
      suffix: .html
#  datasource:
#    data-username: root
#    data-password: mysql
#    url: jdbc:mysql://localhost:3306/myself?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          show-details: ALWAYS