spring:
  application:
    name: CONSUMER
server:
  port: 8021
eureka:
  client:
    service-url:
      defaultZone: http://db-p1000031668.ZZYT.com:8000/eureka/,http://db-p1000031668.ZZYT.com:8001/eureka/,http://db-p1000031668.ZZYT.com:8002/eureka/
feign:
  hystrix:
    enabled: true
#    management:
#      endpoints:
#        web:
#          exposure:
#            include: '*'
#      endpoint:
#        health:
#          show-details: ALWAYS