spring:
  application:
    name: producer
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://db-p1000031668.ZZYT.com:8000/eureka/,http://db-p1000031668.ZZYT.com:8001/eureka/,http://db-p1000031668.ZZYT.com:8002/eureka/
