spring:
  application:
    name: eureka_server
  profiles: eureka1
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/
#      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
#---
#spring:
#  application:
#    name: eureka_server
#  profiles: eureka2
#server:
#  port: 8001
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:8002/eureka/
#---
#spring:
#  application:
#    name: eureka_server
#  profiles: eureka3
#server:
#  port: 8002
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/



